version: 2
jobs:
  build:
    working_directory: ~/washingtondc
  docker:
    - image: fedora:rawhide
  steps:
    - checkout
    - run: mkdir build
    - run: cd build
    - run: cmake ..
    - run: make
